/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IFlareDataConnector {
  export type AttestationResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: BytesLike;
    responseBody: BytesLike;
  };

  export type AttestationResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: string,
    responseBody: string
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: string;
    responseBody: string;
  };

  export type AttestationRequestStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    requestBody: BytesLike;
  };

  export type AttestationRequestStructOutput = [
    attestationType: string,
    sourceId: string,
    requestBody: string
  ] & { attestationType: string; sourceId: string; requestBody: string };
}

export interface IFlareDataConnectorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAttestation"
      | "isAttestationFinalized"
      | "requestAttestation"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAttestationFinalized",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestAttestation",
    values: [IFlareDataConnector.AttestationRequestStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAttestationFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAttestation",
    data: BytesLike
  ): Result;
}

export interface IFlareDataConnector extends BaseContract {
  connect(runner?: ContractRunner | null): IFlareDataConnector;
  waitForDeployment(): Promise<this>;

  interface: IFlareDataConnectorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAttestation: TypedContractMethod<
    [requestId: BytesLike],
    [IFlareDataConnector.AttestationResponseStructOutput],
    "view"
  >;

  isAttestationFinalized: TypedContractMethod<
    [requestId: BytesLike],
    [boolean],
    "view"
  >;

  requestAttestation: TypedContractMethod<
    [request: IFlareDataConnector.AttestationRequestStruct],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [IFlareDataConnector.AttestationResponseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAttestationFinalized"
  ): TypedContractMethod<[requestId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "requestAttestation"
  ): TypedContractMethod<
    [request: IFlareDataConnector.AttestationRequestStruct],
    [string],
    "nonpayable"
  >;

  filters: {};
}
