/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IFTSOv2 {
  export type FeedStruct = {
    votingRoundId: BigNumberish;
    id: BytesLike;
    value: BigNumberish;
    turnoutBIPS: BigNumberish;
    decimals: BigNumberish;
  };

  export type FeedStructOutput = [
    votingRoundId: bigint,
    id: string,
    value: bigint,
    turnoutBIPS: bigint,
    decimals: bigint
  ] & {
    votingRoundId: bigint;
    id: string;
    value: bigint;
    turnoutBIPS: bigint;
    decimals: bigint;
  };
}

export interface IFTSOv2Interface extends Interface {
  getFunction(
    nameOrSignature: "getFeedById" | "getFeedByIdInWei"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getFeedById",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedByIdInWei",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getFeedById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedByIdInWei",
    data: BytesLike
  ): Result;
}

export interface IFTSOv2 extends BaseContract {
  connect(runner?: ContractRunner | null): IFTSOv2;
  waitForDeployment(): Promise<this>;

  interface: IFTSOv2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFeedById: TypedContractMethod<
    [feedId: BytesLike],
    [IFTSOv2.FeedStructOutput],
    "view"
  >;

  getFeedByIdInWei: TypedContractMethod<[feedId: BytesLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getFeedById"
  ): TypedContractMethod<
    [feedId: BytesLike],
    [IFTSOv2.FeedStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeedByIdInWei"
  ): TypedContractMethod<[feedId: BytesLike], [bigint], "view">;

  filters: {};
}
