/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iFlareDataConnectorSol from "./IFlareDataConnector.sol";
export type { iFlareDataConnectorSol };
