/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ClaimProcessor {
  export type ClaimRequestStruct = {
    policyId: BytesLike;
    claimant: AddressLike;
    requestedAmount: BigNumberish;
    submittedAt: BigNumberish;
    status: BigNumberish;
    attestationId: BytesLike;
    evidence: string;
  };

  export type ClaimRequestStructOutput = [
    policyId: string,
    claimant: string,
    requestedAmount: bigint,
    submittedAt: bigint,
    status: bigint,
    attestationId: string,
    evidence: string
  ] & {
    policyId: string;
    claimant: string;
    requestedAmount: bigint;
    submittedAt: bigint;
    status: bigint;
    attestationId: string;
    evidence: string;
  };

  export type ProcessingConfigStruct = {
    minConfirmations: BigNumberish;
    processingDelay: BigNumberish;
    maxBatchSize: BigNumberish;
    autoProcessEnabled: boolean;
  };

  export type ProcessingConfigStructOutput = [
    minConfirmations: bigint,
    processingDelay: bigint,
    maxBatchSize: bigint,
    autoProcessEnabled: boolean
  ] & {
    minConfirmations: bigint;
    processingDelay: bigint;
    maxBatchSize: bigint;
    autoProcessEnabled: boolean;
  };
}

export interface ClaimProcessorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "PROCESSOR_ROLE"
      | "VERIFIER_ROLE"
      | "batchProcess"
      | "claims"
      | "config"
      | "getClaim"
      | "getClaimByPolicy"
      | "getPendingClaimsCount"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "pendingClaims"
      | "policyManager"
      | "policyToClaim"
      | "processAttestation"
      | "renounceRole"
      | "requestAttestation"
      | "revokeRole"
      | "setPolicyManager"
      | "submitClaim"
      | "supportsInterface"
      | "totalClaimsApproved"
      | "totalClaimsProcessed"
      | "totalClaimsRejected"
      | "updateConfig"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchProcessed"
      | "ClaimApproved"
      | "ClaimPaid"
      | "ClaimRejected"
      | "ClaimSubmitted"
      | "ClaimVerified"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROCESSOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchProcess",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claims", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(functionFragment: "getClaim", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getClaimByPolicy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingClaimsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingClaims",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "policyManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "policyToClaim",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processAttestation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestAttestation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPolicyManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitClaim",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalClaimsApproved",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalClaimsProcessed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalClaimsRejected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateConfig",
    values: [ClaimProcessor.ProcessingConfigStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROCESSOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchProcess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claims", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getClaimByPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingClaimsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingClaims",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "policyManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "policyToClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPolicyManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalClaimsApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalClaimsProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalClaimsRejected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateConfig",
    data: BytesLike
  ): Result;
}

export namespace BatchProcessedEvent {
  export type InputTuple = [
    count: BigNumberish,
    approved: BigNumberish,
    rejected: BigNumberish
  ];
  export type OutputTuple = [count: bigint, approved: bigint, rejected: bigint];
  export interface OutputObject {
    count: bigint;
    approved: bigint;
    rejected: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimApprovedEvent {
  export type InputTuple = [claimId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [claimId: string, amount: bigint];
  export interface OutputObject {
    claimId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimPaidEvent {
  export type InputTuple = [
    claimId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    claimId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    claimId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimRejectedEvent {
  export type InputTuple = [claimId: BytesLike, reason: string];
  export type OutputTuple = [claimId: string, reason: string];
  export interface OutputObject {
    claimId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimSubmittedEvent {
  export type InputTuple = [
    claimId: BytesLike,
    policyId: BytesLike,
    claimant: AddressLike
  ];
  export type OutputTuple = [
    claimId: string,
    policyId: string,
    claimant: string
  ];
  export interface OutputObject {
    claimId: string;
    policyId: string;
    claimant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimVerifiedEvent {
  export type InputTuple = [claimId: BytesLike, verified: boolean];
  export type OutputTuple = [claimId: string, verified: boolean];
  export interface OutputObject {
    claimId: string;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClaimProcessor extends BaseContract {
  connect(runner?: ContractRunner | null): ClaimProcessor;
  waitForDeployment(): Promise<this>;

  interface: ClaimProcessorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  PROCESSOR_ROLE: TypedContractMethod<[], [string], "view">;

  VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  batchProcess: TypedContractMethod<[], [void], "nonpayable">;

  claims: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, string, string] & {
        policyId: string;
        claimant: string;
        requestedAmount: bigint;
        submittedAt: bigint;
        status: bigint;
        attestationId: string;
        evidence: string;
      }
    ],
    "view"
  >;

  config: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean] & {
        minConfirmations: bigint;
        processingDelay: bigint;
        maxBatchSize: bigint;
        autoProcessEnabled: boolean;
      }
    ],
    "view"
  >;

  getClaim: TypedContractMethod<
    [claimId: BytesLike],
    [ClaimProcessor.ClaimRequestStructOutput],
    "view"
  >;

  getClaimByPolicy: TypedContractMethod<
    [policyId: BytesLike],
    [ClaimProcessor.ClaimRequestStructOutput],
    "view"
  >;

  getPendingClaimsCount: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  pendingClaims: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  policyManager: TypedContractMethod<[], [string], "view">;

  policyToClaim: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  processAttestation: TypedContractMethod<
    [claimId: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestAttestation: TypedContractMethod<
    [claimId: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setPolicyManager: TypedContractMethod<
    [_policyManager: AddressLike],
    [void],
    "nonpayable"
  >;

  submitClaim: TypedContractMethod<
    [policyId: BytesLike, evidence: string],
    [string],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalClaimsApproved: TypedContractMethod<[], [bigint], "view">;

  totalClaimsProcessed: TypedContractMethod<[], [bigint], "view">;

  totalClaimsRejected: TypedContractMethod<[], [bigint], "view">;

  updateConfig: TypedContractMethod<
    [_config: ClaimProcessor.ProcessingConfigStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PROCESSOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "batchProcess"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claims"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, string, string] & {
        policyId: string;
        claimant: string;
        requestedAmount: bigint;
        submittedAt: bigint;
        status: bigint;
        attestationId: string;
        evidence: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "config"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean] & {
        minConfirmations: bigint;
        processingDelay: bigint;
        maxBatchSize: bigint;
        autoProcessEnabled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClaim"
  ): TypedContractMethod<
    [claimId: BytesLike],
    [ClaimProcessor.ClaimRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClaimByPolicy"
  ): TypedContractMethod<
    [policyId: BytesLike],
    [ClaimProcessor.ClaimRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingClaimsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingClaims"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "policyManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policyToClaim"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "processAttestation"
  ): TypedContractMethod<[claimId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestAttestation"
  ): TypedContractMethod<[claimId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPolicyManager"
  ): TypedContractMethod<[_policyManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitClaim"
  ): TypedContractMethod<
    [policyId: BytesLike, evidence: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalClaimsApproved"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalClaimsProcessed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalClaimsRejected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateConfig"
  ): TypedContractMethod<
    [_config: ClaimProcessor.ProcessingConfigStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BatchProcessed"
  ): TypedContractEvent<
    BatchProcessedEvent.InputTuple,
    BatchProcessedEvent.OutputTuple,
    BatchProcessedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimApproved"
  ): TypedContractEvent<
    ClaimApprovedEvent.InputTuple,
    ClaimApprovedEvent.OutputTuple,
    ClaimApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimPaid"
  ): TypedContractEvent<
    ClaimPaidEvent.InputTuple,
    ClaimPaidEvent.OutputTuple,
    ClaimPaidEvent.OutputObject
  >;
  getEvent(
    key: "ClaimRejected"
  ): TypedContractEvent<
    ClaimRejectedEvent.InputTuple,
    ClaimRejectedEvent.OutputTuple,
    ClaimRejectedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimSubmitted"
  ): TypedContractEvent<
    ClaimSubmittedEvent.InputTuple,
    ClaimSubmittedEvent.OutputTuple,
    ClaimSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimVerified"
  ): TypedContractEvent<
    ClaimVerifiedEvent.InputTuple,
    ClaimVerifiedEvent.OutputTuple,
    ClaimVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "BatchProcessed(uint256,uint256,uint256)": TypedContractEvent<
      BatchProcessedEvent.InputTuple,
      BatchProcessedEvent.OutputTuple,
      BatchProcessedEvent.OutputObject
    >;
    BatchProcessed: TypedContractEvent<
      BatchProcessedEvent.InputTuple,
      BatchProcessedEvent.OutputTuple,
      BatchProcessedEvent.OutputObject
    >;

    "ClaimApproved(bytes32,uint256)": TypedContractEvent<
      ClaimApprovedEvent.InputTuple,
      ClaimApprovedEvent.OutputTuple,
      ClaimApprovedEvent.OutputObject
    >;
    ClaimApproved: TypedContractEvent<
      ClaimApprovedEvent.InputTuple,
      ClaimApprovedEvent.OutputTuple,
      ClaimApprovedEvent.OutputObject
    >;

    "ClaimPaid(bytes32,address,uint256)": TypedContractEvent<
      ClaimPaidEvent.InputTuple,
      ClaimPaidEvent.OutputTuple,
      ClaimPaidEvent.OutputObject
    >;
    ClaimPaid: TypedContractEvent<
      ClaimPaidEvent.InputTuple,
      ClaimPaidEvent.OutputTuple,
      ClaimPaidEvent.OutputObject
    >;

    "ClaimRejected(bytes32,string)": TypedContractEvent<
      ClaimRejectedEvent.InputTuple,
      ClaimRejectedEvent.OutputTuple,
      ClaimRejectedEvent.OutputObject
    >;
    ClaimRejected: TypedContractEvent<
      ClaimRejectedEvent.InputTuple,
      ClaimRejectedEvent.OutputTuple,
      ClaimRejectedEvent.OutputObject
    >;

    "ClaimSubmitted(bytes32,bytes32,address)": TypedContractEvent<
      ClaimSubmittedEvent.InputTuple,
      ClaimSubmittedEvent.OutputTuple,
      ClaimSubmittedEvent.OutputObject
    >;
    ClaimSubmitted: TypedContractEvent<
      ClaimSubmittedEvent.InputTuple,
      ClaimSubmittedEvent.OutputTuple,
      ClaimSubmittedEvent.OutputObject
    >;

    "ClaimVerified(bytes32,bool)": TypedContractEvent<
      ClaimVerifiedEvent.InputTuple,
      ClaimVerifiedEvent.OutputTuple,
      ClaimVerifiedEvent.OutputObject
    >;
    ClaimVerified: TypedContractEvent<
      ClaimVerifiedEvent.InputTuple,
      ClaimVerifiedEvent.OutputTuple,
      ClaimVerifiedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
