/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace FDCFlightVerifier {
  export type FlightEventStruct = {
    flightNumber: string;
    scheduledDeparture: BigNumberish;
    actualDeparture: BigNumberish;
    scheduledArrival: BigNumberish;
    actualArrival: BigNumberish;
    status: BigNumberish;
    delayMinutes: BigNumberish;
    attestationHash: BytesLike;
    verifiedAt: BigNumberish;
  };

  export type FlightEventStructOutput = [
    flightNumber: string,
    scheduledDeparture: bigint,
    actualDeparture: bigint,
    scheduledArrival: bigint,
    actualArrival: bigint,
    status: bigint,
    delayMinutes: bigint,
    attestationHash: string,
    verifiedAt: bigint
  ] & {
    flightNumber: string;
    scheduledDeparture: bigint;
    actualDeparture: bigint;
    scheduledArrival: bigint;
    actualArrival: bigint;
    status: bigint;
    delayMinutes: bigint;
    attestationHash: string;
    verifiedAt: bigint;
  };
}

export declare namespace IEVMTransaction {
  export type RequestBodyStruct = {
    transactionHash: BytesLike;
    requiredConfirmations: BigNumberish;
    provideInput: boolean;
    listEvents: boolean;
    logIndices: BigNumberish[];
  };

  export type RequestBodyStructOutput = [
    transactionHash: string,
    requiredConfirmations: bigint,
    provideInput: boolean,
    listEvents: boolean,
    logIndices: bigint[]
  ] & {
    transactionHash: string;
    requiredConfirmations: bigint;
    provideInput: boolean;
    listEvents: boolean;
    logIndices: bigint[];
  };

  export type EventStruct = {
    logIndex: BigNumberish;
    emitterAddress: AddressLike;
    topics: BytesLike[];
    data: BytesLike;
    removed: boolean;
  };

  export type EventStructOutput = [
    logIndex: bigint,
    emitterAddress: string,
    topics: string[],
    data: string,
    removed: boolean
  ] & {
    logIndex: bigint;
    emitterAddress: string;
    topics: string[];
    data: string;
    removed: boolean;
  };

  export type ResponseBodyStruct = {
    blockNumber: BigNumberish;
    timestamp: BigNumberish;
    sourceAddress: AddressLike;
    isDeployment: boolean;
    receivingAddress: AddressLike;
    value: BigNumberish;
    input: BytesLike;
    status: BigNumberish;
    events: IEVMTransaction.EventStruct[];
  };

  export type ResponseBodyStructOutput = [
    blockNumber: bigint,
    timestamp: bigint,
    sourceAddress: string,
    isDeployment: boolean,
    receivingAddress: string,
    value: bigint,
    input: string,
    status: bigint,
    events: IEVMTransaction.EventStructOutput[]
  ] & {
    blockNumber: bigint;
    timestamp: bigint;
    sourceAddress: string;
    isDeployment: boolean;
    receivingAddress: string;
    value: bigint;
    input: string;
    status: bigint;
    events: IEVMTransaction.EventStructOutput[];
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IEVMTransaction.RequestBodyStruct;
    responseBody: IEVMTransaction.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IEVMTransaction.RequestBodyStructOutput,
    responseBody: IEVMTransaction.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IEVMTransaction.RequestBodyStructOutput;
    responseBody: IEVMTransaction.ResponseBodyStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    data: IEVMTransaction.ResponseStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    data: IEVMTransaction.ResponseStructOutput
  ] & { merkleProof: string[]; data: IEVMTransaction.ResponseStructOutput };
}

export interface FDCFlightVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkClaimEligibility"
      | "flightDataSource"
      | "flightEvents"
      | "getFlightEvent"
      | "isEVMTransactionProofValid"
      | "policyFlightMapping"
      | "setFlightDataSource"
      | "submitFlightData"
      | "verifiedAttestations"
      | "verifyFlightData"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AttestationProcessed" | "FlightDataVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkClaimEligibility",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "flightDataSource",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flightEvents",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFlightEvent",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isEVMTransactionProofValid",
    values: [IEVMTransaction.ProofStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "policyFlightMapping",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFlightDataSource",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitFlightData",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedAttestations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyFlightData",
    values: [IEVMTransaction.ProofStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkClaimEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flightDataSource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flightEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFlightEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isEVMTransactionProofValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "policyFlightMapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFlightDataSource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitFlightData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedAttestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyFlightData",
    data: BytesLike
  ): Result;
}

export namespace AttestationProcessedEvent {
  export type InputTuple = [
    attestationHash: BytesLike,
    success: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    attestationHash: string,
    success: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    attestationHash: string;
    success: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlightDataVerifiedEvent {
  export type InputTuple = [
    flightHash: BytesLike,
    flightNumber: string,
    status: BigNumberish,
    delayMinutes: BigNumberish,
    attestationHash: BytesLike
  ];
  export type OutputTuple = [
    flightHash: string,
    flightNumber: string,
    status: bigint,
    delayMinutes: bigint,
    attestationHash: string
  ];
  export interface OutputObject {
    flightHash: string;
    flightNumber: string;
    status: bigint;
    delayMinutes: bigint;
    attestationHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FDCFlightVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): FDCFlightVerifier;
  waitForDeployment(): Promise<this>;

  interface: FDCFlightVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkClaimEligibility: TypedContractMethod<
    [
      flightNumber: string,
      scheduledDeparture: BigNumberish,
      minimumDelayMinutes: BigNumberish
    ],
    [
      [boolean, bigint, bigint] & {
        eligible: boolean;
        delayMinutes: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  flightDataSource: TypedContractMethod<[], [string], "view">;

  flightEvents: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        flightNumber: string;
        scheduledDeparture: bigint;
        actualDeparture: bigint;
        scheduledArrival: bigint;
        actualArrival: bigint;
        status: bigint;
        delayMinutes: bigint;
        attestationHash: string;
        verifiedAt: bigint;
      }
    ],
    "view"
  >;

  getFlightEvent: TypedContractMethod<
    [flightNumber: string, scheduledDeparture: BigNumberish],
    [FDCFlightVerifier.FlightEventStructOutput],
    "view"
  >;

  isEVMTransactionProofValid: TypedContractMethod<
    [transaction: IEVMTransaction.ProofStruct],
    [boolean],
    "view"
  >;

  policyFlightMapping: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  setFlightDataSource: TypedContractMethod<
    [_newSource: AddressLike],
    [void],
    "nonpayable"
  >;

  submitFlightData: TypedContractMethod<
    [
      flightNumber: string,
      scheduledDeparture: BigNumberish,
      actualDeparture: BigNumberish,
      scheduledArrival: BigNumberish,
      actualArrival: BigNumberish,
      status: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  verifiedAttestations: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  verifyFlightData: TypedContractMethod<
    [_transaction: IEVMTransaction.ProofStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkClaimEligibility"
  ): TypedContractMethod<
    [
      flightNumber: string,
      scheduledDeparture: BigNumberish,
      minimumDelayMinutes: BigNumberish
    ],
    [
      [boolean, bigint, bigint] & {
        eligible: boolean;
        delayMinutes: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "flightDataSource"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "flightEvents"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        flightNumber: string;
        scheduledDeparture: bigint;
        actualDeparture: bigint;
        scheduledArrival: bigint;
        actualArrival: bigint;
        status: bigint;
        delayMinutes: bigint;
        attestationHash: string;
        verifiedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFlightEvent"
  ): TypedContractMethod<
    [flightNumber: string, scheduledDeparture: BigNumberish],
    [FDCFlightVerifier.FlightEventStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isEVMTransactionProofValid"
  ): TypedContractMethod<
    [transaction: IEVMTransaction.ProofStruct],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "policyFlightMapping"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "setFlightDataSource"
  ): TypedContractMethod<[_newSource: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitFlightData"
  ): TypedContractMethod<
    [
      flightNumber: string,
      scheduledDeparture: BigNumberish,
      actualDeparture: BigNumberish,
      scheduledArrival: BigNumberish,
      actualArrival: BigNumberish,
      status: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifiedAttestations"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyFlightData"
  ): TypedContractMethod<
    [_transaction: IEVMTransaction.ProofStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AttestationProcessed"
  ): TypedContractEvent<
    AttestationProcessedEvent.InputTuple,
    AttestationProcessedEvent.OutputTuple,
    AttestationProcessedEvent.OutputObject
  >;
  getEvent(
    key: "FlightDataVerified"
  ): TypedContractEvent<
    FlightDataVerifiedEvent.InputTuple,
    FlightDataVerifiedEvent.OutputTuple,
    FlightDataVerifiedEvent.OutputObject
  >;

  filters: {
    "AttestationProcessed(bytes32,bool,uint64)": TypedContractEvent<
      AttestationProcessedEvent.InputTuple,
      AttestationProcessedEvent.OutputTuple,
      AttestationProcessedEvent.OutputObject
    >;
    AttestationProcessed: TypedContractEvent<
      AttestationProcessedEvent.InputTuple,
      AttestationProcessedEvent.OutputTuple,
      AttestationProcessedEvent.OutputObject
    >;

    "FlightDataVerified(bytes32,string,uint8,uint256,bytes32)": TypedContractEvent<
      FlightDataVerifiedEvent.InputTuple,
      FlightDataVerifiedEvent.OutputTuple,
      FlightDataVerifiedEvent.OutputObject
    >;
    FlightDataVerified: TypedContractEvent<
      FlightDataVerifiedEvent.InputTuple,
      FlightDataVerifiedEvent.OutputTuple,
      FlightDataVerifiedEvent.OutputObject
    >;
  };
}
