/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FTSOv2ConsumerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BTC_USD_ID"
      | "ETH_USD_ID"
      | "FLR_USD_ID"
      | "USDC_USD_ID"
      | "USDT_USD_ID"
      | "addFeedId"
      | "calculateFlrAmount"
      | "calculateUsdValue"
      | "feedIds"
      | "getCurrentFeedValues"
      | "getFeedIds"
      | "getFeedPrice"
      | "getFeedPriceWei"
      | "getFlrUsdPrice"
      | "getFlrUsdPriceWei"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PriceUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "BTC_USD_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ETH_USD_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FLR_USD_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDC_USD_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDT_USD_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addFeedId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateFlrAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateUsdValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feedIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentFeedValues",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedPrice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedPriceWei",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFlrUsdPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFlrUsdPriceWei",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "BTC_USD_ID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ETH_USD_ID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "FLR_USD_ID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "USDC_USD_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDT_USD_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addFeedId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateFlrAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateUsdValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feedIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentFeedValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFeedIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFeedPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedPriceWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFlrUsdPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFlrUsdPriceWei",
    data: BytesLike
  ): Result;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [
    feedId: BytesLike,
    value: BigNumberish,
    decimals: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    feedId: string,
    value: bigint,
    decimals: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    feedId: string;
    value: bigint;
    decimals: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FTSOv2Consumer extends BaseContract {
  connect(runner?: ContractRunner | null): FTSOv2Consumer;
  waitForDeployment(): Promise<this>;

  interface: FTSOv2ConsumerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BTC_USD_ID: TypedContractMethod<[], [string], "view">;

  ETH_USD_ID: TypedContractMethod<[], [string], "view">;

  FLR_USD_ID: TypedContractMethod<[], [string], "view">;

  USDC_USD_ID: TypedContractMethod<[], [string], "view">;

  USDT_USD_ID: TypedContractMethod<[], [string], "view">;

  addFeedId: TypedContractMethod<[feedId: BytesLike], [void], "nonpayable">;

  calculateFlrAmount: TypedContractMethod<
    [usdAmount: BigNumberish],
    [bigint],
    "view"
  >;

  calculateUsdValue: TypedContractMethod<
    [flrAmount: BigNumberish],
    [bigint],
    "view"
  >;

  feedIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getCurrentFeedValues: TypedContractMethod<
    [],
    [
      [bigint[], bigint[], bigint] & {
        _feedValues: bigint[];
        _decimals: bigint[];
        _timestamp: bigint;
      }
    ],
    "view"
  >;

  getFeedIds: TypedContractMethod<[], [string[]], "view">;

  getFeedPrice: TypedContractMethod<
    [feedId: BytesLike],
    [
      [bigint, bigint, bigint] & {
        value: bigint;
        decimals: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFeedPriceWei: TypedContractMethod<
    [feedId: BytesLike],
    [[bigint, bigint] & { value: bigint; timestamp: bigint }],
    "view"
  >;

  getFlrUsdPrice: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        value: bigint;
        decimals: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFlrUsdPriceWei: TypedContractMethod<
    [],
    [[bigint, bigint] & { value: bigint; timestamp: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BTC_USD_ID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ETH_USD_ID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FLR_USD_ID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDC_USD_ID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDT_USD_ID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addFeedId"
  ): TypedContractMethod<[feedId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateFlrAmount"
  ): TypedContractMethod<[usdAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateUsdValue"
  ): TypedContractMethod<[flrAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "feedIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCurrentFeedValues"
  ): TypedContractMethod<
    [],
    [
      [bigint[], bigint[], bigint] & {
        _feedValues: bigint[];
        _decimals: bigint[];
        _timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeedIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getFeedPrice"
  ): TypedContractMethod<
    [feedId: BytesLike],
    [
      [bigint, bigint, bigint] & {
        value: bigint;
        decimals: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeedPriceWei"
  ): TypedContractMethod<
    [feedId: BytesLike],
    [[bigint, bigint] & { value: bigint; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFlrUsdPrice"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        value: bigint;
        decimals: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFlrUsdPriceWei"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { value: bigint; timestamp: bigint }],
    "view"
  >;

  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;

  filters: {
    "PriceUpdated(bytes21,uint256,int8,uint64)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
  };
}
