/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace InsurancePool {
  export type PoolStatsStruct = {
    totalDeposits: BigNumberish;
    totalPremiums: BigNumberish;
    totalPayouts: BigNumberish;
    reserveRatio: BigNumberish;
    utilizationRate: BigNumberish;
  };

  export type PoolStatsStructOutput = [
    totalDeposits: bigint,
    totalPremiums: bigint,
    totalPayouts: bigint,
    reserveRatio: bigint,
    utilizationRate: bigint
  ] & {
    totalDeposits: bigint;
    totalPremiums: bigint;
    totalPayouts: bigint;
    reserveRatio: bigint;
    utilizationRate: bigint;
  };
}

export interface InsurancePoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "OPERATOR_ROLE"
      | "POLICY_MANAGER_ROLE"
      | "claimYield"
      | "collectPremium"
      | "deposit"
      | "depositToken"
      | "distributeYield"
      | "getAvailableLiquidity"
      | "getLPInfo"
      | "getPoolStats"
      | "getRoleAdmin"
      | "getSharePrice"
      | "grantRole"
      | "hasRole"
      | "lastYieldDistribution"
      | "liquidityProviders"
      | "lpList"
      | "maxUtilization"
      | "minDeposit"
      | "pause"
      | "paused"
      | "payClaim"
      | "releaseReserve"
      | "renounceRole"
      | "reservedLiquidity"
      | "revokeRole"
      | "supportsInterface"
      | "totalClaimsPaid"
      | "totalLiquidity"
      | "totalPremiumsCollected"
      | "totalShares"
      | "unpause"
      | "updatePoolParameters"
      | "withdraw"
      | "withdrawalCooldown"
      | "yieldDistributionInterval"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClaimPaid"
      | "LiquidityDeposited"
      | "LiquidityWithdrawn"
      | "Paused"
      | "PoolParametersUpdated"
      | "PremiumCollected"
      | "ReserveUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
      | "YieldDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POLICY_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimYield",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collectPremium",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeYield",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLPInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSharePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastYieldDistribution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityProviders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lpList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxUtilization",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payClaim",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseReserve",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reservedLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalClaimsPaid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPremiumsCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updatePoolParameters",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "yieldDistributionInterval",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POLICY_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimYield", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectPremium",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLPInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSharePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastYieldDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxUtilization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reservedLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalClaimsPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPremiumsCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updatePoolParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldDistributionInterval",
    data: BytesLike
  ): Result;
}

export namespace ClaimPaidEvent {
  export type InputTuple = [
    policyId: BytesLike,
    beneficiary: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    policyId: string,
    beneficiary: string,
    amount: bigint
  ];
  export interface OutputObject {
    policyId: string;
    beneficiary: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityDepositedEvent {
  export type InputTuple = [
    provider: AddressLike,
    amount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [provider: string, amount: bigint, shares: bigint];
  export interface OutputObject {
    provider: string;
    amount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityWithdrawnEvent {
  export type InputTuple = [
    provider: AddressLike,
    amount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [provider: string, amount: bigint, shares: bigint];
  export interface OutputObject {
    provider: string;
    amount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolParametersUpdatedEvent {
  export type InputTuple = [
    minDeposit: BigNumberish,
    maxUtilization: BigNumberish,
    cooldown: BigNumberish
  ];
  export type OutputTuple = [
    minDeposit: bigint,
    maxUtilization: bigint,
    cooldown: bigint
  ];
  export interface OutputObject {
    minDeposit: bigint;
    maxUtilization: bigint;
    cooldown: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PremiumCollectedEvent {
  export type InputTuple = [policyId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [policyId: string, amount: bigint];
  export interface OutputObject {
    policyId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveUpdatedEvent {
  export type InputTuple = [
    policyId: BytesLike,
    reserveAmount: BigNumberish,
    isReserve: boolean
  ];
  export type OutputTuple = [
    policyId: string,
    reserveAmount: bigint,
    isReserve: boolean
  ];
  export interface OutputObject {
    policyId: string;
    reserveAmount: bigint;
    isReserve: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldDistributedEvent {
  export type InputTuple = [totalYield: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [totalYield: bigint, timestamp: bigint];
  export interface OutputObject {
    totalYield: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InsurancePool extends BaseContract {
  connect(runner?: ContractRunner | null): InsurancePool;
  waitForDeployment(): Promise<this>;

  interface: InsurancePoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  POLICY_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  claimYield: TypedContractMethod<[], [void], "nonpayable">;

  collectPremium: TypedContractMethod<
    [policyId: BytesLike, amount: BigNumberish, maxPayout: BigNumberish],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  depositToken: TypedContractMethod<[], [string], "view">;

  distributeYield: TypedContractMethod<[], [void], "nonpayable">;

  getAvailableLiquidity: TypedContractMethod<[], [bigint], "view">;

  getLPInfo: TypedContractMethod<
    [lpAddress: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        depositAmount: bigint;
        shareBalance: bigint;
        currentValue: bigint;
        earnedYield: bigint;
        claimableYield: bigint;
      }
    ],
    "view"
  >;

  getPoolStats: TypedContractMethod<
    [],
    [InsurancePool.PoolStatsStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSharePrice: TypedContractMethod<[], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  lastYieldDistribution: TypedContractMethod<[], [bigint], "view">;

  liquidityProviders: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        depositAmount: bigint;
        shareBalance: bigint;
        lastDepositTime: bigint;
        earnedYield: bigint;
        claimedYield: bigint;
      }
    ],
    "view"
  >;

  lpList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  maxUtilization: TypedContractMethod<[], [bigint], "view">;

  minDeposit: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  payClaim: TypedContractMethod<
    [
      policyId: BytesLike,
      beneficiary: AddressLike,
      amount: BigNumberish,
      maxPayout: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  releaseReserve: TypedContractMethod<
    [policyId: BytesLike, maxPayout: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  reservedLiquidity: TypedContractMethod<[], [bigint], "view">;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalClaimsPaid: TypedContractMethod<[], [bigint], "view">;

  totalLiquidity: TypedContractMethod<[], [bigint], "view">;

  totalPremiumsCollected: TypedContractMethod<[], [bigint], "view">;

  totalShares: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updatePoolParameters: TypedContractMethod<
    [
      _minDeposit: BigNumberish,
      _maxUtilization: BigNumberish,
      _withdrawalCooldown: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[shares: BigNumberish], [void], "nonpayable">;

  withdrawalCooldown: TypedContractMethod<[], [bigint], "view">;

  yieldDistributionInterval: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "POLICY_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimYield"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collectPremium"
  ): TypedContractMethod<
    [policyId: BytesLike, amount: BigNumberish, maxPayout: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "distributeYield"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAvailableLiquidity"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLPInfo"
  ): TypedContractMethod<
    [lpAddress: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        depositAmount: bigint;
        shareBalance: bigint;
        currentValue: bigint;
        earnedYield: bigint;
        claimableYield: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolStats"
  ): TypedContractMethod<[], [InsurancePool.PoolStatsStructOutput], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSharePrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastYieldDistribution"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidityProviders"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        depositAmount: bigint;
        shareBalance: bigint;
        lastDepositTime: bigint;
        earnedYield: bigint;
        claimedYield: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lpList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "maxUtilization"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minDeposit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "payClaim"
  ): TypedContractMethod<
    [
      policyId: BytesLike,
      beneficiary: AddressLike,
      amount: BigNumberish,
      maxPayout: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseReserve"
  ): TypedContractMethod<
    [policyId: BytesLike, maxPayout: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reservedLiquidity"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalClaimsPaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalLiquidity"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPremiumsCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePoolParameters"
  ): TypedContractMethod<
    [
      _minDeposit: BigNumberish,
      _maxUtilization: BigNumberish,
      _withdrawalCooldown: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[shares: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawalCooldown"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yieldDistributionInterval"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "ClaimPaid"
  ): TypedContractEvent<
    ClaimPaidEvent.InputTuple,
    ClaimPaidEvent.OutputTuple,
    ClaimPaidEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityDeposited"
  ): TypedContractEvent<
    LiquidityDepositedEvent.InputTuple,
    LiquidityDepositedEvent.OutputTuple,
    LiquidityDepositedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityWithdrawn"
  ): TypedContractEvent<
    LiquidityWithdrawnEvent.InputTuple,
    LiquidityWithdrawnEvent.OutputTuple,
    LiquidityWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PoolParametersUpdated"
  ): TypedContractEvent<
    PoolParametersUpdatedEvent.InputTuple,
    PoolParametersUpdatedEvent.OutputTuple,
    PoolParametersUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PremiumCollected"
  ): TypedContractEvent<
    PremiumCollectedEvent.InputTuple,
    PremiumCollectedEvent.OutputTuple,
    PremiumCollectedEvent.OutputObject
  >;
  getEvent(
    key: "ReserveUpdated"
  ): TypedContractEvent<
    ReserveUpdatedEvent.InputTuple,
    ReserveUpdatedEvent.OutputTuple,
    ReserveUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "YieldDistributed"
  ): TypedContractEvent<
    YieldDistributedEvent.InputTuple,
    YieldDistributedEvent.OutputTuple,
    YieldDistributedEvent.OutputObject
  >;

  filters: {
    "ClaimPaid(bytes32,address,uint256)": TypedContractEvent<
      ClaimPaidEvent.InputTuple,
      ClaimPaidEvent.OutputTuple,
      ClaimPaidEvent.OutputObject
    >;
    ClaimPaid: TypedContractEvent<
      ClaimPaidEvent.InputTuple,
      ClaimPaidEvent.OutputTuple,
      ClaimPaidEvent.OutputObject
    >;

    "LiquidityDeposited(address,uint256,uint256)": TypedContractEvent<
      LiquidityDepositedEvent.InputTuple,
      LiquidityDepositedEvent.OutputTuple,
      LiquidityDepositedEvent.OutputObject
    >;
    LiquidityDeposited: TypedContractEvent<
      LiquidityDepositedEvent.InputTuple,
      LiquidityDepositedEvent.OutputTuple,
      LiquidityDepositedEvent.OutputObject
    >;

    "LiquidityWithdrawn(address,uint256,uint256)": TypedContractEvent<
      LiquidityWithdrawnEvent.InputTuple,
      LiquidityWithdrawnEvent.OutputTuple,
      LiquidityWithdrawnEvent.OutputObject
    >;
    LiquidityWithdrawn: TypedContractEvent<
      LiquidityWithdrawnEvent.InputTuple,
      LiquidityWithdrawnEvent.OutputTuple,
      LiquidityWithdrawnEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PoolParametersUpdated(uint256,uint256,uint256)": TypedContractEvent<
      PoolParametersUpdatedEvent.InputTuple,
      PoolParametersUpdatedEvent.OutputTuple,
      PoolParametersUpdatedEvent.OutputObject
    >;
    PoolParametersUpdated: TypedContractEvent<
      PoolParametersUpdatedEvent.InputTuple,
      PoolParametersUpdatedEvent.OutputTuple,
      PoolParametersUpdatedEvent.OutputObject
    >;

    "PremiumCollected(bytes32,uint256)": TypedContractEvent<
      PremiumCollectedEvent.InputTuple,
      PremiumCollectedEvent.OutputTuple,
      PremiumCollectedEvent.OutputObject
    >;
    PremiumCollected: TypedContractEvent<
      PremiumCollectedEvent.InputTuple,
      PremiumCollectedEvent.OutputTuple,
      PremiumCollectedEvent.OutputObject
    >;

    "ReserveUpdated(bytes32,uint256,bool)": TypedContractEvent<
      ReserveUpdatedEvent.InputTuple,
      ReserveUpdatedEvent.OutputTuple,
      ReserveUpdatedEvent.OutputObject
    >;
    ReserveUpdated: TypedContractEvent<
      ReserveUpdatedEvent.InputTuple,
      ReserveUpdatedEvent.OutputTuple,
      ReserveUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "YieldDistributed(uint256,uint256)": TypedContractEvent<
      YieldDistributedEvent.InputTuple,
      YieldDistributedEvent.OutputTuple,
      YieldDistributedEvent.OutputObject
    >;
    YieldDistributed: TypedContractEvent<
      YieldDistributedEvent.InputTuple,
      YieldDistributedEvent.OutputTuple,
      YieldDistributedEvent.OutputObject
    >;
  };
}
