/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IAssetManagerControllerInterface extends Interface {
  getFunction(
    nameOrSignature: "assetManagerExists" | "getAssetManagers"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "assetManagerExists",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetManagers",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "assetManagerExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetManagers",
    data: BytesLike
  ): Result;
}

export interface IAssetManagerController extends BaseContract {
  connect(runner?: ContractRunner | null): IAssetManagerController;
  waitForDeployment(): Promise<this>;

  interface: IAssetManagerControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assetManagerExists: TypedContractMethod<
    [_assetManager: AddressLike],
    [boolean],
    "view"
  >;

  getAssetManagers: TypedContractMethod<[], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assetManagerExists"
  ): TypedContractMethod<[_assetManager: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAssetManagers"
  ): TypedContractMethod<[], [string[]], "view">;

  filters: {};
}
