/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFlareDataConnector,
  IFlareDataConnectorInterface,
} from "../../../../contracts/interfaces/IFlareDataConnector.sol/IFlareDataConnector";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "getAttestation",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "attestationType",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "sourceId",
            type: "bytes32",
          },
          {
            internalType: "uint64",
            name: "votingRound",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "lowestUsedTimestamp",
            type: "uint64",
          },
          {
            internalType: "bytes",
            name: "requestBody",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "responseBody",
            type: "bytes",
          },
        ],
        internalType: "struct IFlareDataConnector.AttestationResponse",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "isAttestationFinalized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "attestationType",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "sourceId",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "requestBody",
            type: "bytes",
          },
        ],
        internalType: "struct IFlareDataConnector.AttestationRequest",
        name: "request",
        type: "tuple",
      },
    ],
    name: "requestAttestation",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFlareDataConnector__factory {
  static readonly abi = _abi;
  static createInterface(): IFlareDataConnectorInterface {
    return new Interface(_abi) as IFlareDataConnectorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFlareDataConnector {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IFlareDataConnector;
  }
}
