/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFTSOv2,
  IFTSOv2Interface,
} from "../../../../contracts/interfaces/IFlareDataConnector.sol/IFTSOv2";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes21",
        name: "feedId",
        type: "bytes21",
      },
    ],
    name: "getFeedById",
    outputs: [
      {
        components: [
          {
            internalType: "uint32",
            name: "votingRoundId",
            type: "uint32",
          },
          {
            internalType: "bytes21",
            name: "id",
            type: "bytes21",
          },
          {
            internalType: "int32",
            name: "value",
            type: "int32",
          },
          {
            internalType: "uint16",
            name: "turnoutBIPS",
            type: "uint16",
          },
          {
            internalType: "int8",
            name: "decimals",
            type: "int8",
          },
        ],
        internalType: "struct IFTSOv2.Feed",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes21",
        name: "feedId",
        type: "bytes21",
      },
    ],
    name: "getFeedByIdInWei",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFTSOv2__factory {
  static readonly abi = _abi;
  static createInterface(): IFTSOv2Interface {
    return new Interface(_abi) as IFTSOv2Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFTSOv2 {
    return new Contract(address, _abi, runner) as unknown as IFTSOv2;
  }
}
