/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFTSOv2__factory } from "./IFTSOv2__factory";
export { IFlareDataConnector__factory } from "./IFlareDataConnector__factory";
